function fk = fk_func(theta_1,theta_2,theta_3,theta_4)
%FK_FUNC
%    FK = FK_FUNC(THETA_1,THETA_2,THETA_3,THETA_4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    06-Feb-2026 12:42:09

t2 = theta_3+3.97e+2./5.0;
t3 = (theta_1.*pi)./1.8e+2;
t4 = (theta_4.*pi)./1.8e+2;
t5 = theta_2-3.97e+2./5.0;
t6 = cos(t3);
t7 = cos(t4);
t8 = sin(t3);
t9 = sin(t4);
t10 = (t2.*pi)./1.8e+2;
t11 = (t5.*pi)./1.8e+2;
t12 = cos(t10);
t13 = sin(t10);
t14 = cos(t11);
t15 = sin(t11);
t16 = t12.*t14;
t17 = t13.*t14;
t18 = t12.*t15;
t19 = t13.*t15;
t20 = -t19;
t21 = t6.*t16;
t22 = t6.*t17;
t23 = t6.*t18;
t24 = t8.*t16;
t25 = t6.*t19;
t26 = t8.*t17;
t27 = t8.*t18;
t28 = t8.*t19;
t31 = t17+t18;
t29 = t6.*t20;
t30 = t8.*t20;
t32 = t16+t20;
t33 = t26+t27;
t34 = t22+t23;
t35 = t24+t30;
t36 = t21+t29;
mt1 = [t7.*t36-t9.*t34,t7.*t35-t9.*t33,-t7.*t31-t9.*t32,0.0,-t7.*t34-t9.*t36,-t7.*t33-t9.*t35,-t7.*t32+t9.*t31,0.0,-t8,t6,0.0,0.0,t21.*1.24e+2-t25.*1.24e+2+t6.*t14.*1.3023e+2+t7.*t36.*(6.67e+2./5.0)-t9.*t34.*(6.67e+2./5.0),t24.*1.24e+2-t28.*1.24e+2+t8.*t14.*1.3023e+2+t7.*t35.*(6.67e+2./5.0)-t9.*t33.*(6.67e+2./5.0)];
mt2 = [t15.*(-1.3023e+2)-t31.*1.24e+2-t7.*t31.*(6.67e+2./5.0)-t9.*t32.*(6.67e+2./5.0)+9.632e+1,1.0];
fk = reshape([mt1,mt2],4,4);
end
